import { type NextPage } from "next";
import Head from "next/head";
import Auth from "../domains/Auth";

const AuthPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>SocialClub - Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth />
    </>
  );
};

export default AuthPage;
