import { type GetServerSideProps, type NextPage } from "next";
import Head from "next/head";
import { getServerAuthSession } from "../server/common/get-server-auth-session";
import Home from "domains/Home";
import DefaultLayout from "components/DefaultLayout";

const HomePage: NextPage = () => {
  return (
    <DefaultLayout>
      <Head>
        <title>SocialClub - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </DefaultLayout>
  );
};

export default HomePage;
HomePage;
export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await getServerAuthSession({ req, res });
  return {
    props: { session },
  };
};
